### ISSUE TITLE
Use swift script into my project

### ISSUE THREAD

**Issue by Coger541** [JettIsOnTheNet/Python-Roku-Remote#1]
Hello @JettIsOnTheNet 

Thanks for the scripts

Can I use the swift script into my project to control the roku smart tv over same wifi ?

**Comment by JettIsOnTheNet** [comment]
Thank you for asking. It is MIT license. Which means you can do whatever you like, just include LICENSE file from this repo in yours and name it ROKU_REMOTE_LICENSE or something. :) Have fun, and come back to show me what you build.

**Comment by Coger541** [comment]
Ok thank you very much and do you know how to open apps like netflix, youtube etc through script ?

BTW do you have any fire tv or vizio tv script for controlling fire or vizio smart tv ?

**Comment by JettIsOnTheNet** [comment]
Sorry. I do not have access to any of those devices, so no. The scripts in this repo are very simplistic. Made for example and to be called via shell script from automation such as OpenHAB.

To open or control Apps, you need to use the app launch calls located at the Roku API reference below for ECP commands. There are more available to launch by app_id, close apps, get data from apps to display on remote etc.

The API reference is here for Fire TV apps:
https://developer.amazon.com/docs/video-skills-fire-tv-apps/reference.html

You will have to search for an API reference for Vizio device or contact manufacturer for their developer documentation. They probably have a developer portal you can sign up for.

That is where I retrieved the information for ROKU API.
https://developer.roku.com/docs/developer-program/dev-tools/external-control-api.md

**Comment by Coger541** [comment]
Hello @JettIsOnTheNet 

Thank you very much, that is very helpful information

**Comment by Coger541** [comment]
Hello @JettIsOnTheNet 

Can you please tell me how to find different apps Id like netflix, youtube,  prime video for roku to use at here to open specific app

http://$ROKU_DEV_TARGET:8060/launch/8378



Or can you please provide me apps Id for these apps, I will be very thankful for this

1. Netflix

2. YouTube

3.Apple TV

4.HBO

5.Prime Video

6.Hulu

7.Spotify

8.Disney+

9.Paramount

10.Starz

11.Crunchyroll

12. Peacock

13. Discovery Plus

14. Fubo

15.Showtime

16.Tubi

**Comment by JettIsOnTheNet** [comment]
This is for issues. It is not a support line. You need to figure out these issues on your own, that is part of being a programmer.
